### ISSUE TITLE
NameError: uninitialized constant Sass

### ISSUE THREAD

**Issue by calj** [danielbayerlein/middleman-casper#16]
I'm getting the following when creating a brand new website:

```
NameError: uninitialized constant Sass
Did you mean?  SassC
	/home/calj/.rvm/gems/ruby-2.6.5/gems/middleman-sprockets-4.1.1/lib/middleman-sprockets/resource.rb:90:in `css_response'
	/home/calj/.rvm/gems/ruby-2.6.5/gems/middleman-sprockets-4.1.1/lib/middleman-sprockets/resource.rb:67:in `source'
	/home/calj/.rvm/gems/ruby-2.6.5/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	/home/calj/.rvm/gems/ruby-2.6.5/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	/home/calj/.rvm/gems/ruby-2.6.5/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	/home/calj/.rvm/gems/ruby-2.6.5/gems/middleman-sprockets-4.1.1/lib/middleman-sprockets/resource.rb:30:in `block in render'
	/home/calj/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:170:in `instrument'
	/home/calj/.rvm/gems/ruby-2.6.5/gems/middleman-core-4.3.11/lib/middleman-core/util.rb:21:in `instrument'
	/home/calj/.rvm/gems/ruby-2.6.5/gems/middleman-sprockets-4.1.1/lib/middleman-sprockets/resource.rb:29:in `render'
	/home/calj/.rvm/gems/ruby-2.6.5/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	/home/calj/.rvm/gems/ruby-2.6.5/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	/home/calj/.rvm/gems/ruby-2.6.5/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	/home/calj/.rvm/gems/ruby-2.6.5/gems/middleman-core-4.3.11/lib/middleman-core/rack.rb:113:in `process_request'
	/home/calj/.rvm/gems/ruby-2.6.5/gems/middleman-core-4.3.11/lib/middleman-core/rack.rb:67:in `block in call'
	/home/calj/.rvm/gems/ruby-2.6.5/gems/middleman-core-4.3.11/lib/middleman-core/rack.rb:66:in `catch'
	/home/calj/.rvm/gems/ruby-2.6.5/gems/middleman-core-4.3.11/lib/middleman-core/rack.rb:66:in `call'
```

**Comment by danielbayerlein** [comment]
@calj This is not a issue of the theme. Looks like a problem of `middleman-sprockets`, see https://github.com/middleman/middleman-sprockets/issues/132.
